### ISSUE TITLE
Why recreate ....

### ISSUE THREAD

**Issue by corpxongithub** [MeteorBits/plans-stripe#1]
Why recreate the wheel?  seems like extending a...:roles package saves you work and allows you to focus on the stripe integration.  Also, other modules supporting or extending that roles package are popping up.  (Iron router integration, tasks/perms etc )  Integrating with that will yield you more users, testers etc.  otherwise you'll be taking on too much on your own to remain competitive with other roles packages.  

Lastly as other permissions/roles packages pop up, you might be able to support multiple.   Just a thought.  Either way, great to see people contributing. : )

**Comment by aaronthorp** [comment]
there are a few in the atmosphere, but none yet that can support enough of stripe functions that i needed like quantity based subscriptions, prorate and non-prorate plans as well as fixed billing dates which I plan to work into this package, it is more for my project and if anyone else can use it then great!
